gitRepoUrl = "https://github.com/wiindsom/HyperDigits"
gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Fully Open Source Under The MIT License."

[docusaurus]
title = "HyperDigits"
tagline = "A bignum library forked from"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

[docusaurus.themeConfig.navbar]
title = "HyperDigits"

[[docusaurus.themeConfig.navbar.items]]
to = "/docs/intro"
label = "Docs"
position = "left"

[[docusaurus.themeConfig.navbar.items]]
to = "/features"
label = "Features"
position = "left"

[[docusaurus.themeConfig.navbar.items]]
to = "/api/Public"
label = "API"
position = "left"